import { StyleSheet } from 'react-native';
import { SCREEN_HEIGHT } from '../constants/bagConstants';

export const bagStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F6F6F6',
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: '600',
    color: '#000000',
    textAlign: 'center',
  },
  headerSpacer: {
    width: 40,
  },
  scrollView: {
    flex: 1,
  },
  cartContainer: {
    // Removed paddingHorizontal since we handle it in individual items
  },
  cartItemContainer: {
    position: 'relative',
    marginBottom: 16,
  },
  deleteButtonContainer: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    width: 120,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FF5252',
    zIndex: 1,
  },
  deleteButton: {
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
    width: '100%',
  },
  deleteButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  cartItem: {
    flexDirection: 'row',
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F6F6F6',
    backgroundColor: '#FFFFFF',
    zIndex: 2,
  },
  itemImageContainer: {
    width: 80,
    height: 80,
    marginRight: 12,
  },
  itemImage: {
    width: '100%',
    height: '100%',
    borderRadius: 8,
    backgroundColor: '#F6F6F6',
  },
  itemImagePlaceholder: {
    width: '100%',
    height: '100%',
    borderRadius: 8,
    backgroundColor: '#F6F6F6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  placeholderText: {
    fontSize: 32,
  },
  itemDetails: {
    flex: 1,
  },
  itemName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000000',
    marginBottom: 4,
  },
  itemDescription: {
    fontSize: 14,
    color: '#767676',
    marginBottom: 4,
  },
  itemSize: {
    fontSize: 12,
    color: '#BABABA',
    marginBottom: 2,
  },
  itemColor: {
    fontSize: 12,
    color: '#BABABA',
    marginBottom: 12,
  },
  itemControls: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  quantityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#F6F6F6',
    borderRadius: 6,
    marginRight: 12,
  },
  quantityText: {
    fontSize: 14,
    color: '#000000',
    marginRight: 4,
  },
  sizeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#F6F6F6',
    borderRadius: 6,
    marginRight: 12,
  },
  sizeText: {
    fontSize: 14,
    color: '#000000',
    marginRight: 4,
  },
  dropdownIcon: {
    fontSize: 10,
    color: '#767676',
  },
  itemPrice: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000000',
    marginLeft: 'auto',
  },
  deliverySection: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F6F6F6',
  },
  deliveryTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000000',
    marginBottom: 8,
  },
  deliveryText: {
    fontSize: 14,
    color: '#767676',
    marginBottom: 4,
  },
  deliveryLocationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  deliveryLocationIcon: {
    fontSize: 14,
    marginRight: 4,
  },
  deliveryLocationText: {
    fontSize: 14,
    color: '#767676',
    flex: 1,
  },
  editLocationButton: {
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  editLocationText: {
    fontSize: 14,
    color: '#000000',
    fontWeight: '500',
    textDecorationLine: 'underline',
  },
  pointsSection: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F6F6F6',
  },
  pointsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: '#BABABA',
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxChecked: {
    backgroundColor: '#4CAF50',
    borderColor: '#4CAF50',
  },
  checkmark: {
    fontSize: 12,
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  pointsText: {
    fontSize: 14,
    color: '#000000',
    fontWeight: '500',
    flex: 1,
  },
  pointsSubtext: {
    fontSize: 12,
    color: '#767676',
  },
  promoSection: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F6F6F6',
  },
  promoTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000000',
    marginBottom: 12,
  },
  promoInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F6F6F6',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 4,
  },
  promoInput: {
    flex: 1,
    fontSize: 14,
    color: '#000000',
    paddingVertical: 12,
  },
  applyButton: {
    backgroundColor: '#000000',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 6,
  },
  applyButtonDisabled: {
    backgroundColor: '#BABABA',
  },
  applyButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  applyButtonTextDisabled: {
    color: '#FFFFFF',
  },
  appliedPromoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 12,
    padding: 12,
    backgroundColor: '#E8F5E8',
    borderRadius: 8,
  },
  appliedPromoText: {
    fontSize: 14,
    color: '#4CAF50',
    fontWeight: '500',
  },
  removePromoText: {
    fontSize: 14,
    color: '#FF5252',
    fontWeight: '500',
  },
  summarySection: {
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  summaryLabel: {
    fontSize: 14,
    color: '#767676',
  },
  summaryValue: {
    fontSize: 14,
    color: '#000000',
  },
  totalRow: {
    borderTopWidth: 1,
    borderTopColor: '#F6F6F6',
    paddingTop: 12,
    marginTop: 8,
  },
  totalLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000000',
  },
  totalValue: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000000',
  },
  checkoutContainer: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#F6F6F6',
  },
  checkoutButton: {
    backgroundColor: '#000000',
    paddingVertical: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  checkoutText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  // Modal Styles
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(207, 207, 207, 0.5)',
  },
  modalContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    maxHeight: SCREEN_HEIGHT * 0.6,
  },
  dragHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#767676',
    borderRadius: 30,
    alignSelf: 'center',
    marginTop: 14,
    marginBottom: 20,
  },
  modalContent: {
    paddingHorizontal: 16,
    paddingBottom: 20,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#000000',
    textAlign: 'center',
    marginBottom: 20,
  },
  quantityList: {
    maxHeight: 200,
  },
  quantityOption: {
    paddingVertical: 16,
    paddingHorizontal: 20,
    backgroundColor: '#F6F6F6',
    marginBottom: 8,
    borderRadius: 8,
    alignItems: 'center',
  },
  selectedQuantityOption: {
    backgroundColor: '#F6F6F6',
    borderWidth: 2,
    borderColor: '#000000',
  },
  quantityOptionText: {
    fontSize: 16,
    color: '#BABABA',
  },
  selectedQuantityOptionText: {
    color: '#000000',
    fontWeight: '600',
  },
  sizeList: {
    maxHeight: 200,
  },
  sizeOption: {
    paddingVertical: 16,
    paddingHorizontal: 20,
    backgroundColor: '#F6F6F6',
    marginBottom: 8,
    borderRadius: 8,
    alignItems: 'center',
  },
  selectedSizeOption: {
    backgroundColor: '#F6F6F6',
    borderWidth: 2,
    borderColor: '#000000',
  },
  sizeOptionText: {
    fontSize: 16,
    color: '#BABABA',
  },
  selectedSizeOptionText: {
    color: '#000000',
    fontWeight: '600',
  },
  sizeChartLink: {
    alignSelf: 'center',
    marginVertical: 16,
  },
  sizeChartText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#000000',
    textDecorationLine: 'underline',
  },
  doneButton: {
    backgroundColor: '#000000',
    paddingVertical: 16,
    borderRadius: 100,
    alignItems: 'center',
    marginTop: 20,
  },
  doneButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  // Size Chart Modal Styles
  sizeChartModalContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    maxHeight: SCREEN_HEIGHT * 0.8,
  },
  tabContainer: {
    flexDirection: 'row',
    marginBottom: 20,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  activeTab: {
    borderBottomColor: '#000000',
  },
  tabText: {
    fontSize: 16,
    color: '#BABABA',
  },
  activeTabText: {
    color: '#000000',
    fontWeight: '600',
  },
  tabContent: {
    flex: 1,
  },
  sizeChartContent: {
    padding: 16,
  },
  sizeChartSubtitle: {
    fontSize: 14,
    color: '#000000',
    marginBottom: 8,
  },
  unitSelector: {
    flexDirection: 'row',
    marginBottom: 20,
    alignSelf: 'flex-end',
  },
  unitButton: {
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 16,
    marginLeft: 8,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  selectedUnitButton: {
    backgroundColor: '#000000',
    borderColor: '#000000',
  },
  unitButtonText: {
    fontSize: 12,
    color: '#767676',
    fontWeight: '600',
  },
  selectedUnitButtonText: {
    color: '#FFFFFF',
  },
  sizeTable: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    overflow: 'hidden',
    marginTop: 20,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#000000',
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  tableHeaderText: {
    flex: 1,
    fontSize: 12,
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F6F6F6',
  },
  tableCellText: {
    flex: 1,
    fontSize: 14,
    color: '#000000',
    textAlign: 'center',
    fontWeight: '400',
  },
  lastTableRow: {
    borderBottomWidth: 0,
  },
  measureContent: {
    padding: 16,
  },
  measureText: {
    fontSize: 14,
    color: '#767676',
    lineHeight: 20,
  },
  // Promo Success Modal Styles
  promoSuccessModalContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  promoSuccessContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 32,
    alignItems: 'center',
    maxWidth: 300,
    width: '100%',
  },
  successIconContainer: {
    marginBottom: 24,
  },
  successIcon: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#4CAF50',
    justifyContent: 'center',
    alignItems: 'center',
  },
  successCheckmark: {
    fontSize: 24,
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  promoSuccessTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#000000',
    marginBottom: 8,
    textAlign: 'center',
  },
  promoSuccessDescription: {
    fontSize: 14,
    color: '#767676',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 24,
  },
  promoSuccessDoneButton: {
    backgroundColor: '#000000',
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 8,
    width: '100%',
    alignItems: 'center',
  },
  promoSuccessDoneButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  // Empty bag styles
  emptyBagContainer: {
    flex: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 120,
    paddingBottom: 40,
  },
  emptyBagContent: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  emptyBagIcon: {
    marginBottom: 24,
  },
  bagIconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 2,
    borderColor: '#000000',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  bagIconText: {
    fontSize: 32,
  },
  emptyBagTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#000000',
    marginBottom: 8,
    textAlign: 'center',
  },
  emptyBagSubtitle: {
    fontSize: 16,
    color: '#666666',
    textAlign: 'center',
    lineHeight: 22,
  },
  shopNowButton: {
    backgroundColor: '#000000',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 24,
    width: '100%',
    alignItems: 'center',
    marginBottom: 20,
  },
  shopNowButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
});
