import { StyleSheet } from 'react-native';
import { SCREEN_HEIGHT } from '../constants/bagConstants';

export const bagStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#FFFFFF',
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: '500',
    color: '#000000',
    textAlign: 'center',
    fontFamily: 'Montserrat-Medium',
  },
  headerSpacer: {
    width: 40,
  },
  scrollView: {
    flex: 1,
  },
  cartContainer: {
    // Removed padding as items handle their own spacing
  },
  cartItemContainer: {
    position: 'relative',
    // Removed marginBottom for tighter spacing like Figma
  },
  deleteButtonContainer: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    width: 120,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FF5252',
    zIndex: 1,
  },
  deleteButton: {
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
    width: '100%',
  },
  deleteButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  cartItem: {
    paddingVertical: 24,
    paddingHorizontal: 16,
    backgroundColor: '#FFFFFF',
    zIndex: 2,
  },
  productRow: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  itemImageContainer: {
    width: 80,
    height: 80,
    marginRight: 16,
    borderRadius: 8,
    backgroundColor: '#F6F6F6',
  },
  itemImage: {
    width: '100%',
    height: '100%',
    borderRadius: 8,
    backgroundColor: '#F6F6F6',
  },
  itemImagePlaceholder: {
    width: '100%',
    height: '100%',
    borderRadius: 8,
    backgroundColor: '#F6F6F6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  placeholderText: {
    fontSize: 32,
  },
  itemDetails: {
    flex: 1,
    justifyContent: 'flex-start',
  },
  itemName: {
    fontSize: 14,
    fontWeight: '500',
    color: '#000000',
    marginBottom: 4,
    fontFamily: 'Montserrat-Medium',
  },
  itemDescription: {
    fontSize: 14,
    color: '#767676',
    marginBottom: 2,
    fontFamily: 'Montserrat-Regular',
    lineHeight: 17,
  },
  itemSize: {
    fontSize: 14,
    color: '#767676',
    fontFamily: 'Montserrat-Regular',
  },
  itemControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  quantityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  quantityText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#000000',
    marginRight: 16,
    fontFamily: 'Montserrat-Medium',
  },
  sizeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sizeText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#000000',
    marginRight: 16,
    fontFamily: 'Montserrat-Medium',
  },
  dropdownIcon: {
    fontSize: 14,
    color: '#000000',
  },
  itemPrice: {
    fontSize: 16,
    fontWeight: '500',
    color: '#000000',
    fontFamily: 'Montserrat-Medium',
  },
  deliverySection: {
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  deliveryTitle: {
    fontSize: 16,
    fontWeight: '500',
    color: '#000000',
    marginBottom: 4,
    fontFamily: 'Montserrat-Medium',
  },
  deliveryText: {
    fontSize: 16,
    color: '#000000',
    marginBottom: 4,
    fontFamily: 'Montserrat-Regular',
  },
  deliveryLocationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  deliverySubText: {
    fontSize: 16,
    color: '#000000',
    marginRight: 8,
    fontFamily: 'Montserrat-Regular',
  },
  editLocationButton: {
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  editLocationText: {
    fontSize: 16,
    color: '#000000',
    fontWeight: '500',
    textDecorationLine: 'underline',
    fontFamily: 'Montserrat-Medium',
  },
  pointsSection: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#E4E4E4',
  },
  pointsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 3,
    borderWidth: 1,
    borderColor: '#BCBCBC',
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxChecked: {
    backgroundColor: '#111111',
    borderColor: '#111111',
  },
  checkmark: {
    fontSize: 10,
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  pointsText: {
    fontSize: 16,
    color: '#000000',
    fontWeight: '500',
    fontFamily: 'Montserrat-Medium',
  },
  pointsSubtext: {
    fontSize: 10,
    color: '#6C6C6C',
    marginLeft: 32,
    fontFamily: 'Montserrat-Regular',
  },
  promoSection: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E4E4E4',
  },
  promoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  promoTitle: {
    fontSize: 16,
    fontWeight: '500',
    color: '#000000',
    fontFamily: 'Montserrat-Medium',
  },
  promoIcon: {
    fontSize: 14,
    color: '#000000',
  },
  promoCouponCard: {
    backgroundColor: '#F6F6F6',
    borderRadius: 8,
    padding: 24,
    position: 'relative',
    marginBottom: 12,
  },
  couponHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  couponDiscount: {
    fontSize: 25,
    fontWeight: '600',
    color: '#292929',
    fontFamily: 'Montserrat-SemiBold',
  },
  couponDates: {
    fontSize: 10,
    color: '#6C6C6C',
    fontFamily: 'Montserrat-Regular',
  },
  couponCode: {
    fontSize: 12,
    color: '#6C6C6C',
    marginBottom: 16,
    fontFamily: 'Montserrat-Regular',
  },
  couponDivider: {
    height: 1,
    backgroundColor: '#000000',
    marginHorizontal: -24,
    marginBottom: 16,
    borderStyle: 'dashed',
  },
  couponApplyButton: {
    alignSelf: 'center',
  },
  couponApplyText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#7F7F7F',
    fontFamily: 'Montserrat-Medium',
  },
  appliedPromoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 12,
    padding: 12,
    backgroundColor: '#E8F5E8',
    borderRadius: 8,
  },
  appliedPromoText: {
    fontSize: 14,
    color: '#4CAF50',
    fontWeight: '500',
  },
  removePromoText: {
    fontSize: 14,
    color: '#FF5252',
    fontWeight: '500',
  },
  summarySection: {
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  summaryLabel: {
    fontSize: 16,
    color: '#767676',
    fontFamily: 'Montserrat-Regular',
  },
  summaryValue: {
    fontSize: 16,
    color: '#767676',
    fontFamily: 'Montserrat-Regular',
  },
  totalRow: {
    borderTopWidth: 1,
    borderTopColor: '#E4E4E4',
    paddingTop: 12,
    marginTop: 8,
    marginBottom: 0,
  },
  totalLabel: {
    fontSize: 16,
    fontWeight: '500',
    color: '#000000',
    fontFamily: 'Montserrat-Medium',
  },
  totalValue: {
    fontSize: 16,
    fontWeight: '500',
    color: '#000000',
    fontFamily: 'Montserrat-Medium',
  },
  paymentMethodsSection: {
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  paymentMethodsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  paymentMethodText: {
    fontSize: 10,
    color: '#848688',
    fontWeight: '800',
    fontFamily: 'Montserrat-ExtraBold',
  },
  checkoutContainer: {
    paddingHorizontal: 22,
    paddingVertical: 16,
    backgroundColor: '#FFFFFF',
  },
  checkoutButton: {
    backgroundColor: '#000000',
    paddingVertical: 16,
    borderRadius: 100,
    alignItems: 'center',
    marginBottom: 20,
  },
  checkoutText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#FFFFFF',
    fontFamily: 'Montserrat-Medium',
  },
  // Modal Styles
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: SCREEN_HEIGHT * 0.6,
  },
  dragHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#E0E0E0',
    borderRadius: 30,
    alignSelf: 'center',
    marginTop: 14,
    marginBottom: 20,
  },
  modalContent: {
    paddingHorizontal: 24,
    paddingBottom: 34,
  },
  modalContentNoTitle: {
    paddingHorizontal: 0,
    paddingBottom: 34,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#000000',
    textAlign: 'center',
    marginBottom: 32,
  },
  quantityList: {
    maxHeight: 200,
    marginBottom: 32,
  },
  quantityListContent: {
    flexGrow: 1,
  },
  scrollSpacer: {
    height: 70, // Half of modal view height minus half item height for perfect centering
  },
  quantityOption: {
    paddingVertical: 0,
    paddingHorizontal: 0,
    backgroundColor: 'transparent',
    marginBottom: 0,
    borderRadius: 0,
    alignItems: 'center',
  },
  quantityOptionInner: {
    width: '100%',
    paddingVertical: 20,
    paddingHorizontal: 20,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quantityOptionInnerFullWidth: {
    width: '100%',
    paddingVertical: 20,
    paddingHorizontal: 24,
    borderRadius: 0,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 0,
  },
  quantityOptionInnerFullWidthSelected: {
    width: '100%',
    paddingVertical: 20,
    paddingHorizontal: 24,
    borderRadius: 0,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 0,
    backgroundColor: '#F0F0F0',
  },
  removeOption: {
    marginBottom: 0,
    paddingHorizontal: 24,
  },
  selectedQuantityOption: {
    backgroundColor: 'transparent',
    borderWidth: 0,
  },
  quantityOptionText: {
    fontSize: 18,
    color: '#000000',
    fontWeight: '400',
    letterSpacing: 0.5,
  },
  selectedQuantityOptionText: {
    color: '#000000',
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  removeOptionText: {
    fontSize: 16,
    color: '#808080',
    fontWeight: '400',
    letterSpacing: 0.3,
  },
  selectedRemoveOptionText: {
    fontSize: 16,
    color: '#FF4444', // Red color when Remove is selected
    fontWeight: '600',
    letterSpacing: 0.3,
  },
  sizeList: {
    maxHeight: 200,
  },
  sizeOption: {
    paddingVertical: 16,
    paddingHorizontal: 20,
    backgroundColor: '#F6F6F6',
    marginBottom: 8,
    borderRadius: 8,
    alignItems: 'center',
  },
  selectedSizeOption: {
    backgroundColor: '#F6F6F6',
    borderWidth: 2,
    borderColor: '#000000',
  },
  sizeOptionText: {
    fontSize: 16,
    color: '#BABABA',
  },
  selectedSizeOptionText: {
    color: '#000000',
    fontWeight: '600',
  },
  sizeChartLink: {
    alignSelf: 'flex-end',
    marginVertical: 16,
    marginHorizontal: 24,
  },
  sizeChartText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#000000',
    textDecorationLine: 'underline',
  },
  doneButton: {
    backgroundColor: '#000000',
    paddingVertical: 18,
    borderRadius: 25,
    alignItems: 'center',
    marginTop: 0,
    marginHorizontal: 24,
  },
  doneButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  // Size Chart Modal Styles
  sizeChartModalContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    maxHeight: SCREEN_HEIGHT * 0.8,
  },
  tabContainer: {
    flexDirection: 'row',
    marginBottom: 20,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  activeTab: {
    borderBottomColor: '#000000',
  },
  tabText: {
    fontSize: 16,
    color: '#BABABA',
  },
  activeTabText: {
    color: '#000000',
    fontWeight: '600',
  },
  tabContent: {
    flex: 1,
  },
  sizeChartContent: {
    padding: 16,
  },
  sizeChartSubtitle: {
    fontSize: 14,
    color: '#000000',
    marginBottom: 8,
  },
  unitSelector: {
    flexDirection: 'row',
    marginBottom: 20,
    alignSelf: 'flex-end',
  },
  unitButton: {
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 16,
    marginLeft: 8,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  selectedUnitButton: {
    backgroundColor: '#000000',
    borderColor: '#000000',
  },
  unitButtonText: {
    fontSize: 12,
    color: '#767676',
    fontWeight: '600',
  },
  selectedUnitButtonText: {
    color: '#FFFFFF',
  },
  sizeTable: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    overflow: 'hidden',
    marginTop: 20,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#000000',
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  tableHeaderText: {
    flex: 1,
    fontSize: 12,
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F6F6F6',
  },
  tableCellText: {
    flex: 1,
    fontSize: 14,
    color: '#000000',
    textAlign: 'center',
    fontWeight: '400',
  },
  lastTableRow: {
    borderBottomWidth: 0,
  },
  measureContent: {
    padding: 16,
  },
  measureText: {
    fontSize: 14,
    color: '#767676',
    lineHeight: 20,
  },
  // Promo Success Modal Styles
  promoSuccessModalContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  promoSuccessContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 32,
    alignItems: 'center',
    maxWidth: 300,
    width: '100%',
  },
  successIconContainer: {
    marginBottom: 24,
  },
  successIcon: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#4CAF50',
    justifyContent: 'center',
    alignItems: 'center',
  },
  successCheckmark: {
    fontSize: 24,
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  promoSuccessTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#000000',
    marginBottom: 8,
    textAlign: 'center',
  },
  promoSuccessDescription: {
    fontSize: 14,
    color: '#767676',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 24,
  },
  promoSuccessDoneButton: {
    backgroundColor: '#000000',
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 8,
    width: '100%',
    alignItems: 'center',
  },
  promoSuccessDoneButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  // Empty bag styles
  emptyBagContainer: {
    flex: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 120,
    paddingBottom: 40,
  },
  emptyBagContent: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  emptyBagIcon: {
    marginBottom: 24,
  },
  bagIconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 2,
    borderColor: '#000000',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  bagIconText: {
    fontSize: 32,
  },
  emptyBagTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#000000',
    marginBottom: 8,
    textAlign: 'center',
  },
  emptyBagSubtitle: {
    fontSize: 16,
    color: '#666666',
    textAlign: 'center',
    lineHeight: 22,
  },
  shopNowButton: {
    backgroundColor: '#000000',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 24,
    width: '100%',
    alignItems: 'center',
    marginBottom: 20,
  },
  shopNowButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
});
